name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository co
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust version
        run: |
          cargo --version
          rustc --version

      - name: Run rustfmt check
        run: cargo fmt --all -- --check
        working-directory: ./

      - name: Run clippy check and deny warnings
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: ./
